import os

commands = {
    'ls': 'dir',
    'mv': 'ren',
    'cp': 'copy',
    'mv': 'move',
    'clear': 'cls',
    'rm': 'del',
    'diff': 'fc',
    'grep': 'find',
    'man': '/?',
    'pwd': 'chdir',
    'date': 'time',
    'cd': 'cd',
    'mkdir': 'md',
    'echo': 'echo',
    'vim': 'edit',
    'exit': 'exit',
    'mke2fs': 'format',
    'mformat': 'format',
    'mem': 'free',
    'rm -rf/rmdir': 'rmdir',
    'kill': 'taskkill',
    'ps x': 'tasklist',
    'export': 'set',
    'chown': 'attrib',
    'chmod': 'attrib',
    'traceroute': 'tracert',
    'cron': 'at',
    'cat': 'type',
    'ping': 'ping',
    'nslookup': 'nslookup',
    'du -s': 'chdisk',
    'ls -R': 'tree'
}
